# Generated by Django 5.2.4 on 2025-07-22 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('PLANNED', 'Planifié'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('POSTPONED', 'Reporté')], default='PLANNED', max_length=20)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_organises', to=settings.AUTH_USER_MODEL)),
                ('participants_parents', models.ManyToManyField(blank=True, related_name='appointments', to='parents.parent')),
                ('participants_students', models.ManyToManyField(blank=True, related_name='appointments', to='students.student')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_heure_debut'],
            },
        ),
    ]
