# Generated by Django 5.2.4 on 2025-07-22 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='niveau_etudes',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.level'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students_suivis', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
